### PR TITLE
Release 7.3.0

### PR DESCRIPTION
**Pull request by h-lame**
Includes code to strip personally identifiable information (PII) from arguments
sent to the google analytics (GA) tracker (see: #435) and some dependency
updates (see: #444).

### CODE REVIEW

**Comment by 36degrees** [comment]
This will also include the changes in #444 – sorry, I should have to the changelog as part of that PR.

**Comment by h-lame** [comment]
@36degrees - I'll add something to this PR for you.

**Comment by 36degrees** [comment]
Appreciated, thanks!

**Comment by h-lame** [comment]
No worries.  Done in a rebase.

**Pull request merged**
