### PR TITLE
Mobile-first typography

### PR DESCRIPTION
**Pull request by gemmaleigh**
- Set `$font-size-640` and `$line-height-640` first
- Override with `$font-size` and `$line-height` for larger screens
- Do `$is-print` check last, to override any font-size set with `$font-size-print`

### CODE REVIEW

**Comment by edds** [comment]
The problem with doing that is font sizes in older versions of Internet Explorer which don't understand media queries will be getting small font-sizes.

**Comment by gemmaleigh** [comment]
I thought that by setting the $is-ie: true; flag in each IE_8/7.6/.scss file, when using the @media mixin from the _conditionals.scss file, then IE will get all the styles declared in the media block - so those declared last - the larger sizes will override the smaller sizes.

**Comment by edds** [comment]
This isn't using the media mixin due to limitations in Sass. This is using a pure `@media` approach.

**Comment by edds** [comment]
You could possibly get around it by using the if IE stuff for this. If you wanted to still print out the bigger sizes for IE.

**Comment by gemmaleigh** [comment]
Sorry @edds my mistake. I'll amend it to do the `$is-ie` check here.

**Comment by alicebartlett** [comment]
[comment from the frontend meeting] @edds are you happy to merge this now or do you have further comments?

**Pull request merged**
